# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         BerkeleyDB-SecIndices-Accessor
version:      0.03
version_from: lib/BerkeleyDB/SecIndices/Accessor.pm
installdirs:  site
requires:
    BerkeleyDB:                    0.27
    File::Temp:                    0.16
    Storable:                      2.15
    YAML:                          0.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
